# Generated by Django 4.2.6 on 2023-11-15 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climatisation', models.BooleanField(default=False)),
                ('toit_ouvrant', models.BooleanField(default=False)),
                ('radio', models.BooleanField(default=False)),
                ('retroviseurs_electrique', models.BooleanField(default=False)),
                ('alarm', models.BooleanField(default=False)),
                ('boite_auto', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='voiture_photo/')),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mark', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('annee', models.IntegerField(validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2023)])),
                ('energie', models.CharField(choices=[('diesel', 'Diesel'), ('essence', 'Essence'), ('gpl', 'GPL')], max_length=10)),
                ('couleur', models.CharField(max_length=50)),
                ('kilometrage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField()),
                ('prix', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000000)])),
                ('wilaya', models.CharField(choices=[('01', 'Adrar'), ('02', 'Chlef'), ('03', 'Laghouat'), ('04', 'Oum El Bouaghi'), ('05', 'Batna'), ('06', 'Béjaïa'), ('07', 'Biskra'), ('08', 'Béchar'), ('09', 'Blida'), ('10', 'Bouira'), ('11', 'Tamanrasset'), ('12', 'Tébessa'), ('13', 'Tlemcen'), ('14', 'Tiaret'), ('15', 'Tizi Ouzou'), ('16', 'Alger'), ('17', 'Djelfa'), ('18', 'Jijel'), ('19', 'Sétif'), ('20', 'Saïda'), ('21', 'Skikda'), ('22', 'Sidi Bel Abbès'), ('23', 'Annaba'), ('24', 'Guelma'), ('25', 'Constantine'), ('26', 'Médéa'), ('27', 'Mostaganem'), ('28', 'MSila'), ('29', 'Mascara'), ('30', 'Ouargla'), ('31', 'Oran'), ('32', 'El Bayadh'), ('33', 'Illizi'), ('34', 'Bordj Bou Arreridj'), ('35', 'Boumerdès'), ('36', 'El Tarf'), ('37', 'Tindouf'), ('38', 'Tissemsilt'), ('39', 'El Oued'), ('40', 'Khenchela'), ('41', 'Souk Ahras'), ('42', 'Tipaza'), ('43', 'Mila'), ('44', 'Aïn Defla'), ('45', 'de Naâma'), ('46', 'Aïn Témouchent'), ('47', 'de Ghardaïa'), ('48', 'de Relizane'), ('49', 'de Timimoun'), ('50', 'de Bordj Badji Mokhtar'), ('51', 'Ouled Djellal'), ('52', 'de Béni Abbès'), ('53', 'In Salah'), ('54', 'In Guezzam'), ('55', 'de Touggourt'), ('56', 'de Djanet'), ('57', 'El MGhair'), ('58', 'El Menia')], default='Inconnu', max_length=50)),
                ('options', models.ManyToManyField(to='annonce.option')),
            ],
        ),
    ]
