# Generated by Django 4.2.6 on 2023-11-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_appuser_is_staff_alter_appuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
