# Generated by Django 4.2.6 on 2023-11-24 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_alter_appuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='username',
        ),
        migrations.AddField(
            model_name='appuser',
            name='nom',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='prenom',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='phone',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits and start with 05, 06, or 07.', regex='^0[5-7]\\d{8}$')]),
        ),
    ]
